### PR TITLE
Make "Succeeded" Pods report OK status instead of Failed

### PR DESCRIPTION
**Pull request by 9strands**
Added check that counts a pod in a state that is 'Succeeded' as a passing result, instead of failed.  The script currently counts it incorrectly as failed and warns on Pods that are in Succeeded and have successfully accomplished their function.

### CODE REVIEW

**Comment by erikdsjostrom** [comment]
This looks like a good idea, and probably an oversight on our part. I would like to see a test case for this though, something like this would probably do the trick, but feel free to come up with even more if you'd like.

`tests/test_pods.py`
```
def test_check_succeeded(pod_full):
    pod_full["status"]["phase"] = "Succeeded"
    assert check_pods([pod_full]).output.state == NaemonState.OK
```
Good work!

**Comment by 9strands** [comment]
Hi, @erikdsjostrom - I really don't understand how to use test-cases, or how they work in this instance.  What exactly does your snippet do that enables us to verify the case without having a cluster that has items in Successful state?

**Comment by erikdsjostrom** [comment]
What the whole test suit does is that it mocks (https://en.wikipedia.org/wiki/Mock_object) such a cluster, in order for us to run some specific test to verify functionality. What the actual snippet does is that it takes such a mocked object, sets the state/phase of the object to "Succeeded" and verifies that if we were to check this pod the output would be OK, this is what I understood to be the change you want to introduce with your PR. What it does in the future is guarantee that this new feature will always hold true.

**Comment by 9strands** [comment]
Aha, makes sense.  How do I execute the testing functionality locally in this repo so I can see if the snippet I create in the test suite actually works?

**Comment by 9strands** [comment]
I see pytest in them, when I try to execute pytest in the master branch - I get 6 errors, one for each test file in the tests directory.

**Comment by erikdsjostrom** [comment]
You could either:
1. Look at the file `op5build/ci_config.yml` and everything following line 3 should get you up and running with the tests, just make sure to use python3.6.
2. Write the test and push it, and Travis will test it out for you.

**Comment by 9strands** [comment]
Hi, @erikdsjostrom - I'm obviously not running something correctly, because I get the error below for every one of the test files.  There's got to be something that I'm doing wrong.
 
 user@dev_vm  ~/projects/check_k8s   pod_successful_state  poetry run pytest
Creating virtualenv check-k8s-Ex79S1GL-py3.10 in /home/user/.cache/pypoetry/virtualenvs
==================================================================================== test session starts ====================================================================================
platform linux -- Python 3.10.2, pytest-6.2.4, py-1.11.0, pluggy-0.13.1
rootdir: /home/user/projects/check_k8s
collected 0 items / 6 errors                                                                                                                                                                

========================================================================================== ERRORS ===========================================================================================
____________________________________________________________________________ ERROR collecting tests/test_cli.py _____________________________________________________________________________
ImportError while importing test module '/home/user/projects/check_k8s/tests/test_cli.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib64/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_cli.py:3: in <module>
    from k8s.cli import parse_cmdline, Default
E   ModuleNotFoundError: No module named 'k8s'

**Comment by 9strands** [comment]
So, I moved the k8s module into my local python3.10 site-packages directory in my homedir in the .venv and upgraded both pluggy and pytest in the .venv that poetry created... now the tests run.

**Comment by erikdsjostrom** [comment]
Alright, looking good! I'll clean up the commits and make sure it passes our internal build systems as well.

Strange about the tests, but at least you got it working.

**Comment by erikdsjostrom** [comment]
This has been merged as of [7d5bf16](https://github.com/ITRS-Group/check_k8s/commit/7d5bf166525d289f818ae0dda59d48a5f22ab895). Thanks @9strands!

**Pull request closed without merging**
